# sign-commit = false
# sign-tag = false
# push = true
# publish = true

tag-message= "chore: release {{crate_name}} version {{version}}"
tag-prefix = "v"
pre-release-hook = """
echo "Pre-Release Hook" &&
git cliff -o CHANGELOG.md --tag {{version}} &&
git add CHANGELOG.md &&
git commit -m 'chore: update changelog for {{version}}'
"""
