# sign-commit = false
# sign-tag = false
# push = true
# publish = true

tag-message= "chore: release {{crate_name}} version {{version}}"
pre-release-hook = "sh -c 'echo Pre-Release Hook; git cliff -o CHANGELOG.md --tag {{version}}'"
